name: flutter_auth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.0
  lottie: ^2.6.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  decorated_dropdownbutton: ^0.0.3
  csc_picker: ^0.2.7
  google_fonts: ^2.0.0
  # cupertino_icons: ^0.1.3
  # lottie: ^0.7.0+1
  # pin_entry_text_field: ^0.1.4

  # dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  provider: ^6.0.5
  curved_navigation_bar: ^1.0.3
  simple_sidebar: ^0.0.8
  animated_sidebar: ^1.0.1
  side_bar_custom: ^1.0.3
  flutter_advanced_drawer: ^1.3.5
  google_maps_flutter: ^2.5.0
  expandable_text: ^2.3.0
  easy_image_viewer: ^1.2.1
  insta_image_viewer: ^1.0.2
  lite_rolling_switch: ^1.0.1
  buttons_panel: ^1.0.0
  dropdown_button2: ^2.3.9
  image_picker: ^0.8.4+4
  range_slider_dialog: ^0.0.3
  cupertino_range_slider_improved: ^2.0.1
  flutter_xlider: ^3.5.0
  range_slider_flutter: ^0.0.2
  multiple_images_picker: ^1.0.1
  dash_chat_2: ^0.0.19
  group_list_view: ^1.1.1
  awesome_notifications: ^0.8.2
  booking_calendar: ^1.1.10
  intl: ^0.18.1
  syncfusion_flutter_calendar: ^23.2.6
  location: ^4.1.1
  dio: ^5.4.0
  socket_io_client: ^2.0.3+1
  geocoding: ^2.1.1
  flutter_paypal_checkout: ^1.0.1
  flutter_inappwebview: ^5.8.0
  flutter_polyline_points: ^1.0.0
  comment_box: ^0.0.18
  geolocator: ^10.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  # flutter_stripe: ^9.3.0
  syncfusion_flutter_charts: ^23.2.7
  radio_grouped_buttons: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: UbuntuMono
      fonts:
        - asset: fonts\UbuntuMono-Bold.ttf
        - asset: fonts\UbuntuMono-BoldItalic.ttf
        - asset: fonts\UbuntuMono-Italic.ttf
        - asset: fonts\UbuntuMono-Regular.ttf

    - family: MyIcons
      fonts:
        - asset: fonts/MyFlutterApp.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
