/**
 * @file Automatically generated by barrelsby.
 */

export * from "./appointmentController";
export * from "./chatbotController";
export * from "./commentController";
export * from "./HelloWorldController";
export * from "./notificationController";
export * from "./propertyController";
export * from "./recommendationController";
export * from "./savedPropertyController";
export * from "./searchController";
export * from "./UserController";
